spring:
  datasource:
    url: jdbc:mysql://182.254.242.96:3306/fdmusicplatform?characterEncoding=utf-8&serverTimezone=UTC
    username: developer
    password: feidian52.com
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.arcmin.domain

#server:
#  address: 182.254.242.96
#  port: 3666